server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ExcelData2
    username: postgres
    password: 1811786
  jpa:
    hibernate:
      ddl-auto: create-drop
    property:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
