server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exceldata2
    username: postgres
    password: 1811786
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    property:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  main:
    web-application-type: servlet

#openapi: 3.0.0
#info:
#  title: Some API
#  version: "1"
#
#paths:
#  /upload:
#    post:
#      requestBody:
#        content:
#          multipart/form-data:
#            schema:
#              type: object
#              properties:
#                file:
#                  type: string
#                  format: binary
#      responses:
#        '200':
#          description: OK
#          content:
#            text/plain:
#              schema:
#                type: string
#                example: "File upload successful"